// cp1_6.13_auto33/src/IdeaDetail.tsx
import { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';

interface Comment {
  id: number;
  author: string;
  authorAvatar: string;
  content: string;
  createdAt: string;
}

interface Idea {
  id: number;
  title: string;
  description: string;
  tags: string[];
  likes: number;
  liked: boolean;
  status: string;
  author: string;
  authorAvatar: string;
  createdAt: string;
  comments: Comment[];
}

const TAG_COLORS: Record<string, string> = {
  '文化': '#E8A87C',
  '科技': '#85C7DE',
  '生活': '#95D1CC',
  '艺术': '#D291BC',
};

const detailStyles = `
  @keyframes pulse {
    0% { transform: scale(1); }
    50% { transform: scale(1.2); }
    100% { transform: scale(1); }
  }

  @keyframes floatUp {
    0% { transform: translateY(0) scale(1); opacity: 1; }
    100% { transform: translateY(-60px) scale(0.3); opacity: 0; }
  }

  @keyframes commentSlideUp {
    0% { transform: translateY(20px); opacity: 0; }
    100% { transform: translateY(0); opacity: 1; }
  }

  .detail-page {
    min-height: 100vh;
    background: #F7F1E0;
    transform: translateX(100%);
    opacity: 0;
    transition: transform 350ms cubic-bezier(0.4, 0, 0.2, 1), opacity 350ms cubic-bezier(0.4, 0, 0.2, 1);
  }
  .detail-page.entered {
    transform: translateX(0);
    opacity: 1;
  }

  .detail-like-btn {
    display: flex;
    align-items: center;
    gap: 6px;
    border: none;
    border-radius: 20px;
    padding: 8px 20px;
    cursor: pointer;
    font-size: 16px;
    font-weight: 700;
    font-family: 'Nunito', sans-serif;
    transition: background 0.2s;
  }
  .detail-like-btn.liked {
    background: #FF6B6B;
    color: #fff;
  }
  .detail-like-btn.not-liked {
    background: rgba(255,107,107,0.12);
    color: #FF6B6B;
  }
  .detail-like-btn.pulse {
    animation: pulse 0.4s ease;
  }

  .detail-star {
    position: fixed;
    pointer-events: none;
    font-size: 20px;
    z-index: 9999;
    animation: floatUp 1s ease-out forwards;
  }

  .comment-item {
    display: flex;
    gap: 12px;
    margin-bottom: 14px;
  }
  .comment-item.new-comment {
    animation: commentSlideUp 300ms cubic-bezier(0.4, 0, 0.2, 1) forwards;
  }
  .comment-avatar {
    width: 36px;
    height: 36px;
    border-radius: 50%;
    border: 2px solid rgba(255,255,255,0.8);
    flex-shrink: 0;
    margin-top: 2px;
  }
  .comment-bubble {
    background: #f0f0f0;
    border-radius: 0 16px 16px 16px;
    padding: 12px 16px;
    flex: 1;
  }
  .comment-author {
    font-size: 13px;
    font-weight: 700;
    color: #555;
    margin-bottom: 4px;
    font-family: 'Nunito', sans-serif;
  }
  .comment-time {
    font-weight: 400;
    color: #aaa;
    margin-left: 8px;
    font-size: 11px;
  }
  .comment-text {
    font-size: 14px;
    color: #444;
    line-height: 1.6;
    font-family: 'Nunito', sans-serif;
  }

  .comment-input-wrap {
    display: flex;
    gap: 10px;
    margin-bottom: 20px;
    background: #fff;
    border-radius: 16px;
    padding: 14px 16px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.04);
  }
  .comment-input {
    flex: 1;
    border: none;
    outline: none;
    font-size: 14px;
    font-family: 'Nunito', sans-serif;
    color: #333;
    background: transparent;
  }
  .comment-send-btn {
    background: #FF6B6B;
    color: #fff;
    border: none;
    border-radius: 14px;
    padding: 8px 18px;
    font-size: 13px;
    font-weight: 700;
    cursor: pointer;
    font-family: 'Nunito', sans-serif;
    transition: background 0.2s;
  }
  .comment-send-btn:disabled {
    background: #f0c0c0;
    cursor: not-allowed;
  }

  .status-btn {
    display: flex;
    align-items: center;
    gap: 6px;
    border: none;
    border-radius: 20px;
    padding: 8px 20px;
    cursor: pointer;
    font-size: 14px;
    font-weight: 700;
    font-family: 'Nunito', sans-serif;
    transition: background 0.2s;
  }
  .status-btn.achieved {
    background: #4CAF50;
    color: #fff;
  }
  .status-btn.pending {
    background: rgba(76,175,80,0.12);
    color: #4CAF50;
  }

  .back-btn {
    background: none;
    border: none;
    font-size: 22px;
    cursor: pointer;
    padding: 4px 8px;
    border-radius: 10px;
    transition: background 0.2s;
  }
  .back-btn:hover {
    background: rgba(0,0,0,0.05);
  }
`;

export default function IdeaDetail() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [idea, setIdea] = useState<Idea | null>(null);
  const [commentText, setCommentText] = useState('');
  const [isLiking, setIsLiking] = useState(false);
  const [entered, setEntered] = useState(false);
  const [stars, setStars] = useState<{ sid: number; x: number; y: number }[]>([]);
  const [newCommentId, setNewCommentId] = useState<number | null>(null);
  const starIdRef = useRef(0);

  useEffect(() => {
    if (!id) return;
    axios
      .get<Idea>(`/api/ideas/${id}`)
      .then((res) => {
        setIdea(res.data);
        requestAnimationFrame(() => {
          requestAnimationFrame(() => {
            setEntered(true);
          });
        });
      })
      .catch(() => navigate('/'));
  }, [id, navigate]);

  const handleLike = async (e: React.MouseEvent) => {
    if (!idea || isLiking) return;
    const rect = (e.currentTarget as HTMLElement).getBoundingClientRect();
    const x = rect.left + rect.width / 2 - 10;
    const y = rect.top - 5;
    const sid = ++starIdRef.current;

    setStars((prev) => [...prev, { sid, x, y }]);
    setIsLiking(true);

    setTimeout(() => {
      setStars((prev) => prev.filter((s) => s.sid !== sid));
    }, 1000);
    setTimeout(() => setIsLiking(false), 400);

    try {
      const res = await axios.post(`/api/ideas/${idea.id}/like`);
      setIdea((prev) => (prev ? { ...prev, likes: res.data.likes, liked: res.data.liked } : prev));
    } catch {
      // ignore
    }
  };

  const handleStatusToggle = async () => {
    if (!idea) return;
    const newStatus = idea.status === '已实现' ? '萌芽' : '已实现';
    try {
      await axios.patch(`/api/ideas/${idea.id}/status`, { status: newStatus });
      setIdea((prev) => (prev ? { ...prev, status: newStatus } : prev));
    } catch {
      // ignore
    }
  };

  const handleComment = async () => {
    if (!idea || !commentText.trim()) return;
    try {
      const res = await axios.post(`/api/ideas/${idea.id}/comments`, {
        author: '匿名灵感家',
        authorAvatar: 'https://api.dicebear.com/7.x/fun-emoji/svg?seed=anon',
        content: commentText.trim(),
      });
      setIdea((prev) => (prev ? { ...prev, comments: [...prev.comments, res.data] } : prev));
      setNewCommentId(res.data.id);
      setCommentText('');
      setTimeout(() => setNewCommentId(null), 300);
    } catch {
      // ignore
    }
  };

  if (!idea) {
    return (
      <div style={{ textAlign: 'center', padding: 80, color: '#bbb', fontSize: 18, fontWeight: 600, fontFamily: 'Nunito, sans-serif' }}>
        加载中...
      </div>
    );
  }

  return (
    <div className={`detail-page ${entered ? 'entered' : ''}`}>
      <style>{detailStyles}</style>

      {stars.map((s) => (
        <span key={s.sid} className="detail-star" style={{ left: s.x, top: s.y }}>
          ⭐
        </span>
      ))}

      <header
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 12,
          padding: '18px 24px',
          background: 'rgba(255,255,255,0.6)',
          backdropFilter: 'blur(10px)',
          borderBottom: '1px solid rgba(0,0,0,0.06)',
          position: 'sticky',
          top: 0,
          zIndex: 100,
        }}
      >
        <button className="back-btn" onClick={() => navigate('/')}>
          ← 返回
        </button>
        <h2
          style={{
            fontSize: 18,
            fontWeight: 800,
            color: '#FF6B6B',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            whiteSpace: 'nowrap',
          }}
        >
          {idea.title}
        </h2>
      </header>

      <div style={{ maxWidth: 720, margin: '0 auto', padding: '28px 20px 60px' }}>
        <div
          style={{
            background: 'linear-gradient(135deg, #FFECD2 0%, #FCB69F 40%, #A1C4FD 100%)',
            borderRadius: 22,
            padding: '28px 24px 22px',
            marginBottom: 24,
            boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}>
            <img
              src={idea.authorAvatar}
              alt={idea.author}
              style={{ width: 44, height: 44, borderRadius: '50%', border: '3px solid rgba(255,255,255,0.7)' }}
            />
            <div>
              <div style={{ fontSize: 15, fontWeight: 700, color: '#444' }}>{idea.author}</div>
              <div style={{ fontSize: 12, color: '#888', fontWeight: 600 }}>
                {new Date(idea.createdAt).toLocaleDateString('zh-CN')}
              </div>
            </div>
            {idea.status === '已实现' && (
              <span
                style={{
                  marginLeft: 'auto',
                  fontSize: 12,
                  fontWeight: 700,
                  background: '#4CAF50',
                  color: '#fff',
                  padding: '4px 14px',
                  borderRadius: 12,
                }}
              >
                ✓ 已实现
              </span>
            )}
          </div>

          <h1 style={{ fontSize: 24, fontWeight: 800, color: '#222', marginBottom: 12, lineHeight: 1.4 }}>
            {idea.title}
          </h1>
          <p style={{ fontSize: 15, color: '#444', lineHeight: 1.7, marginBottom: 16 }}>
            {idea.description}
          </p>

          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 18 }}>
            {idea.tags.map((tag) => (
              <span
                key={tag}
                style={{
                  fontSize: 12,
                  fontWeight: 700,
                  padding: '4px 14px',
                  borderRadius: 12,
                  background: TAG_COLORS[tag] || '#ddd',
                  color: '#fff',
                }}
              >
                {tag}
              </span>
            ))}
          </div>

          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 12,
              borderTop: '1px solid rgba(0,0,0,0.08)',
              paddingTop: 16,
            }}
          >
            <button
              className={`detail-like-btn ${idea.liked ? 'liked' : 'not-liked'} ${isLiking ? 'pulse' : ''}`}
              onClick={handleLike}
            >
              {idea.liked ? '❤️' : '🤍'} {idea.likes}
            </button>
            <button
              className={`status-btn ${idea.status === '已实现' ? 'achieved' : 'pending'}`}
              onClick={handleStatusToggle}
            >
              {idea.status === '已实现' ? '✓ 已实现' : '🌱 标为已实现'}
            </button>
          </div>
        </div>

        <div>
          <h3 style={{ fontSize: 18, fontWeight: 800, color: '#333', marginBottom: 16, fontFamily: 'Nunito, sans-serif' }}>
            💬 评论 ({idea.comments.length})
          </h3>

          <div className="comment-input-wrap">
            <input
              className="comment-input"
              value={commentText}
              onChange={(e) => setCommentText(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && commentText.trim()) handleComment();
              }}
              placeholder="说点什么..."
            />
            <button
              className="comment-send-btn"
              onClick={handleComment}
              disabled={!commentText.trim()}
            >
              发送
            </button>
          </div>

          {idea.comments.length === 0 && (
            <div style={{ textAlign: 'center', color: '#bbb', fontSize: 14, fontWeight: 600, padding: '20px 0', fontFamily: 'Nunito, sans-serif' }}>
              还没有评论，来说点什么吧 🌟
            </div>
          )}

          {idea.comments.map((comment) => (
            <div
              key={comment.id}
              className={`comment-item ${newCommentId === comment.id ? 'new-comment' : ''}`}
            >
              <img className="comment-avatar" src={comment.authorAvatar} alt={comment.author} />
              <div className="comment-bubble">
                <div className="comment-author">
                  {comment.author}
                  <span className="comment-time">
                    {new Date(comment.createdAt).toLocaleDateString('zh-CN')}
                  </span>
                </div>
                <div className="comment-text">{comment.content}</div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// cp1_6.11_auto16/src/components/IdeaDetail.vue
<template>
  <Teleport to="body">
    <Transition name="modal">
      <div v-if="visible" class="modal-overlay" @click.self="$emit('close')">
        <div class="modal-content">
          <button class="close-btn" @click="$emit('close')">
            <span>✕</span>
          </button>

          <div class="detail-header">
            <div class="avatar" :style="{ backgroundColor: avatarInfo.color }">
              <span class="avatar-emoji">{{ avatarInfo.emoji }}</span>
            </div>
            <div class="author-info">
              <span class="author-name">{{ idea.authorName }}</span>
              <span class="post-time">{{ formatTime(idea.createdAt) }}</span>
            </div>
          </div>

          <h2 class="detail-title">{{ idea.title }}</h2>
          <p class="detail-description">{{ idea.description }}</p>

          <div class="chart-section">
            <h3 class="section-title">投票统计</h3>
            <div class="bar-chart">
              <div class="bar-item">
                <div class="bar-label">
                  <span class="bar-icon">👍</span>
                  <span>赞</span>
                </div>
                <div class="bar-track">
                  <div 
                    class="bar-fill up" 
                    :style="{ height: barHeights.up + '%' }"
                  >
                    <span class="bar-value">{{ idea.votes.up }}</span>
                  </div>
                </div>
              </div>
              <div class="bar-item">
                <div class="bar-label">
                  <span class="bar-icon">🤔</span>
                  <span>中立</span>
                </div>
                <div class="bar-track">
                  <div 
                    class="bar-fill neutral" 
                    :style="{ height: barHeights.neutral + '%' }"
                  >
                    <span class="bar-value">{{ idea.votes.neutral }}</span>
                  </div>
                </div>
              </div>
              <div class="bar-item">
                <div class="bar-label">
                  <span class="bar-icon">👎</span>
                  <span>踩</span>
                </div>
                <div class="bar-track">
                  <div 
                    class="bar-fill down" 
                    :style="{ height: barHeights.down + '%' }"
                  >
                    <span class="bar-value">{{ idea.votes.down }}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="comment-section">
            <h3 class="section-title">评论区 ({{ idea.comments.length }})</h3>
            
            <div class="comment-input-wrapper">
              <div class="input-avatar" :style="{ backgroundColor: currentAvatarInfo.color }">
                <span>{{ currentAvatarInfo.emoji }}</span>
              </div>
              <div class="input-area">
                <textarea 
                  v-model="newComment" 
                  placeholder="写下你的想法... (最多50字)"
                  maxlength="50"
                  @keydown.enter.ctrl="submitComment"
                ></textarea>
                <div class="input-actions">
                  <span class="char-count">{{ newComment.length }}/50</span>
                  <button 
                    class="submit-btn" 
                    :disabled="!newComment.trim()"
                    @click="submitComment"
                  >
                    发表评论
                  </button>
                </div>
              </div>
            </div>

            <div class="comments-list">
              <TransitionGroup name="comment">
                <div 
                  v-for="comment in sortedComments" 
                  :key="comment.id"
                  class="comment-item"
                >
                  <div class="comment-avatar" :style="{ backgroundColor: parseAvatar(comment.authorAvatar).color }">
                    <span>{{ parseAvatar(comment.authorAvatar).emoji }}</span>
                  </div>
                  <div class="comment-bubble">
                    <div class="comment-header">
                      <span class="comment-author">{{ comment.authorName }}</span>
                      <span class="comment-time">{{ formatTime(comment.createdAt) }}</span>
                    </div>
                    <p class="comment-content">{{ comment.content }}</p>
                  </div>
                </div>
              </TransitionGroup>
              
              <div v-if="idea.comments.length === 0" class="no-comments">
                暂无评论，来发表第一条评论吧！
              </div>
            </div>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import type { Idea } from '@/composables/useIdeas'

const props = defineProps<{
  visible: boolean
  idea: Idea
  formatTime: (timestamp: number) => string
  parseAvatar: (avatar: string) => { color: string; emoji: string }
  currentUserAvatar: string
}>()

const emit = defineEmits<{
  close: []
  addComment: [ideaId: string, content: string]
}>()

const newComment = ref('')

const avatarInfo = computed(() => props.parseAvatar(props.idea.authorAvatar))
const currentAvatarInfo = computed(() => props.parseAvatar(props.currentUserAvatar))

const maxVotes = computed(() => {
  return Math.max(props.idea.votes.up, props.idea.votes.neutral, props.idea.votes.down, 1)
})

const barHeights = computed(() => ({
  up: (props.idea.votes.up / maxVotes.value) * 100,
  neutral: (props.idea.votes.neutral / maxVotes.value) * 100,
  down: (props.idea.votes.down / maxVotes.value) * 100
}))

const sortedComments = computed(() => {
  return [...props.idea.comments].sort((a, b) => b.createdAt - a.createdAt)
})

function submitComment() {
  if (!newComment.value.trim()) return
  emit('addComment', props.idea.id, newComment.value)
  newComment.value = ''
}

watch(() => props.visible, (val) => {
  if (val) {
    document.body.style.overflow = 'hidden'
  } else {
    document.body.style.overflow = ''
  }
})
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.7);
  backdrop-filter: blur(8px);
  -webkit-backdrop-filter: blur(8px);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
  padding: 20px;
}

.modal-content {
  background: var(--primary-bg);
  border: 1px solid var(--glass-border);
  border-radius: 24px;
  padding: 32px;
  max-width: 700px;
  width: 100%;
  max-height: 85vh;
  overflow-y: auto;
  position: relative;
  animation: modalIn 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);
}

@keyframes modalIn {
  from {
    opacity: 0;
    transform: scale(0.9) translateY(20px);
  }
  to {
    opacity: 1;
    transform: scale(1) translateY(0);
  }
}

.close-btn {
  position: absolute;
  top: 16px;
  right: 16px;
  width: 36px;
  height: 36px;
  border-radius: 50%;
  border: none;
  background: rgba(255, 255, 255, 0.1);
  color: var(--text-secondary);
  font-size: 18px;
  cursor: pointer;
  transition: all 0.2s ease;
  display: flex;
  align-items: center;
  justify-content: center;
}

.close-btn:hover {
  background: rgba(255, 107, 107, 0.3);
  color: var(--danger);
  transform: rotate(90deg);
}

.detail-header {
  display: flex;
  align-items: center;
  gap: 16px;
  margin-bottom: 20px;
}

.avatar {
  width: 56px;
  height: 56px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 3px solid rgba(255, 255, 255, 0.2);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
}

.avatar-emoji {
  font-size: 28px;
}

.author-info {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.author-name {
  font-size: 16px;
  font-weight: 700;
  color: var(--text-primary);
}

.post-time {
  font-size: 14px;
  color: var(--text-secondary);
}

.detail-title {
  font-size: 24px;
  font-weight: 800;
  color: var(--text-primary);
  margin: 0 0 16px 0;
  line-height: 1.3;
}

.detail-description {
  font-size: 15px;
  color: var(--text-secondary);
  line-height: 1.8;
  margin: 0 0 28px 0;
  padding: 20px;
  background: rgba(255, 255, 255, 0.03);
  border-radius: 16px;
  border-left: 4px solid var(--accent-yellow);
}

.section-title {
  font-size: 18px;
  font-weight: 700;
  color: var(--text-primary);
  margin: 0 0 20px 0;
  display: flex;
  align-items: center;
  gap: 8px;
}

.section-title::before {
  content: '';
  width: 4px;
  height: 20px;
  background: var(--accent-yellow);
  border-radius: 2px;
}

.chart-section {
  margin-bottom: 32px;
}

.bar-chart {
  display: flex;
  justify-content: space-around;
  align-items: flex-end;
  height: 200px;
  padding: 20px;
  background: rgba(255, 255, 255, 0.03);
  border-radius: 16px;
  gap: 20px;
}

.bar-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
  flex: 1;
}

.bar-label {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;
  font-size: 13px;
  color: var(--text-secondary);
  order: 2;
}

.bar-icon {
  font-size: 20px;
}

.bar-track {
  width: 60px;
  height: 140px;
  background: rgba(255, 255, 255, 0.05);
  border-radius: 12px 12px 4px 4px;
  position: relative;
  overflow: hidden;
  display: flex;
  align-items: flex-end;
  order: 1;
}

.bar-fill {
  width: 100%;
  min-height: 4px;
  border-radius: 12px 12px 4px 4px;
  position: relative;
  transition: height 0.8s cubic-bezier(0.34, 1.56, 0.64, 1);
  display: flex;
  align-items: flex-start;
  justify-content: center;
  padding-top: 8px;
}

.bar-fill.up {
  background: linear-gradient(180deg, #51cf66 0%, #37b24d 50%, #2f9e44 100%);
  box-shadow: 0 0 20px rgba(81, 207, 102, 0.4);
}

.bar-fill.neutral {
  background: linear-gradient(180deg, #ffd43b 0%, #fab005 50%, #f59f00 100%);
  box-shadow: 0 0 20px rgba(255, 212, 59, 0.4);
}

.bar-fill.down {
  background: linear-gradient(180deg, #ff6b6b 0%, #f03e3e 50%, #e03131 100%);
  box-shadow: 0 0 20px rgba(255, 107, 107, 0.4);
}

.bar-value {
  font-size: 14px;
  font-weight: 700;
  color: #fff;
  text-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
}

.comment-section {
  border-top: 1px solid rgba(255, 255, 255, 0.1);
  padding-top: 28px;
}

.comment-input-wrapper {
  display: flex;
  gap: 12px;
  margin-bottom: 24px;
}

.input-avatar {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  border: 2px solid rgba(255, 255, 255, 0.2);
}

.input-avatar span {
  font-size: 18px;
}

.input-area {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

textarea {
  width: 100%;
  min-height: 80px;
  padding: 12px 16px;
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 16px;
  background: rgba(255, 255, 255, 0.03);
  color: var(--text-primary);
  font-size: 14px;
  font-family: inherit;
  resize: none;
  outline: none;
  transition: all 0.2s ease;
}

textarea:focus {
  border-color: var(--accent-yellow);
  background: rgba(255, 212, 59, 0.05);
  box-shadow: 0 0 0 3px rgba(255, 212, 59, 0.1);
}

textarea::placeholder {
  color: var(--text-secondary);
}

.input-actions {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.char-count {
  font-size: 12px;
  color: var(--text-secondary);
}

.submit-btn {
  padding: 8px 20px;
  border: none;
  border-radius: 20px;
  background: var(--accent-yellow);
  color: var(--primary-bg);
  font-size: 14px;
  font-weight: 700;
  cursor: pointer;
  transition: all 0.2s ease;
}

.submit-btn:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(255, 212, 59, 0.4);
}

.submit-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.comments-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.comment-item {
  display: flex;
  gap: 12px;
}

.comment-avatar {
  width: 36px;
  height: 36px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  border: 2px solid rgba(255, 255, 255, 0.2);
}

.comment-avatar span {
  font-size: 16px;
}

.comment-bubble {
  flex: 1;
  background: rgba(255, 255, 255, 0.05);
  border-radius: 0 16px 16px 16px;
  padding: 12px 16px;
  position: relative;
}

.comment-bubble::before {
  content: '';
  position: absolute;
  top: 0;
  left: -8px;
  width: 0;
  height: 0;
  border-top: 12px solid rgba(255, 255, 255, 0.05);
  border-left: 12px solid transparent;
}

.comment-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 6px;
}

.comment-author {
  font-size: 13px;
  font-weight: 600;
  color: var(--accent-yellow);
}

.comment-time {
  font-size: 11px;
  color: var(--text-secondary);
}

.comment-content {
  font-size: 14px;
  color: var(--text-primary);
  line-height: 1.6;
  margin: 0;
  word-break: break-word;
}

.no-comments {
  text-align: center;
  color: var(--text-secondary);
  font-size: 14px;
  padding: 40px 20px;
  background: rgba(255, 255, 255, 0.02);
  border-radius: 16px;
}

.modal-enter-active,
.modal-leave-active {
  transition: opacity 0.3s ease;
}

.modal-enter-from,
.modal-leave-to {
  opacity: 0;
}

.modal-enter-active .modal-content,
.modal-leave-active .modal-content {
  transition: all 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);
}

.modal-enter-from .modal-content,
.modal-leave-to .modal-content {
  opacity: 0;
  transform: scale(0.9) translateY(20px);
}

.comment-enter-active,
.comment-leave-active {
  transition: all 0.3s ease;
}

.comment-enter-from {
  opacity: 0;
  transform: translateX(-20px);
}

.comment-leave-to {
  opacity: 0;
  transform: translateX(20px);
}

.comment-move {
  transition: transform 0.3s ease;
}

@media (max-width: 640px) {
  .modal-content {
    padding: 20px;
    border-radius: 16px;
  }
  
  .detail-title {
    font-size: 20px;
  }
  
  .bar-track {
    width: 45px;
  }
}
</style>
